extends "res://tests/playthrough.gd"
func jump_to(target: Vector3) -> void:
    key(KEY_SPACE,true)
    await frames(3)
    key(KEY_SPACE,false)
    await walk(target)
    await frames(45)
func run() -> void:
    game = load("res://main.tscn").instantiate()
    root.add_child(game)
    current_scene = game
    await frames(5)
    game._primary_action()
    await frames(5)
    await walk(Vector3(-17,0,10))
    await interact()
    check("seed_one",game.seeds_found.size()==1)
    await walk(Vector3(-13,0,-5.3))
    await jump_to(Vector3(-13,.45,-6.65))
    check("jump_first_step",game.player.position.y>.35)
    await jump_to(Vector3(-13,1,-8.7))
    check("jump_terrace",game.player.position.y>.85)
    await walk(Vector3(-13,1,-10))
    await interact()
    check("seed_two",game.seeds_found.size()==2)
    await walk(Vector3(-9,0,-10))
    await walk(Vector3(-7,0,-2))
    await interact()
    await walk(Vector3(1.4,0,-4))
    key(KEY_D,true)
    await frames(160)
    key(KEY_D,false)
    await frames(15)
    check("water_recovery_with_board",game.recoveries>0 and game.carrying==0)
    await walk(Vector3(1.2,0,0))
    await interact()
    await walk(Vector3(-15,0,-5))
    await interact()
    await walk(Vector3(1.5,0,0))
    await interact()
    await walk(Vector3(9,0,0))
    await walk(Vector3(18,0,7))
    await interact()
    check("garden_reward",game.seeds_found.size()==3 and game.garden_saved and game.garden.visible)
    key(KEY_ESCAPE,true)
    await frames(2)
    key(KEY_ESCAPE,false)
    await frames(2)
    var paused_at: Vector3 = game.player.position
    key(KEY_W,true)
    await frames(30)
    key(KEY_W,false)
    check("pause_blocks_movement",game.paused and game.player.position.distance_to(paused_at)<.01)
    game._primary_action()
    await frames(15)
    check("resume_clears_held_input",game.player.position.distance_to(paused_at)<.1)
    game._secondary_action()
    await frames(10)
    game=current_scene
    check("replay_reset",game.bridge_stage==0 and game.carrying==-1 and not game.following and not game.completed)
    check("garden_reload",game.garden_saved and game.garden.visible)
    var file := FileAccess.open(ProjectSettings.globalize_path("res://../../docs/games/block-evidence/native-edge-checks.json"),FileAccess.WRITE)
    file.store_string(JSON.stringify(results,"  "))
    file.close()
    quit(1 if results.values().has(false) else 0)
