extends SceneTree
var failures := 0
func check(ok: bool, label: String) -> void:
    print(("PASS " if ok else "FAIL ")+label)
    if not ok: failures += 1
func _initialize() -> void:
    var c = preload("res://scripts/irrigation_construction.gd").new()
    check(not c.act("place","support"),"no free construction")
    c.act("plan")
    check(not c.act("place","support"),"insufficient stock cannot bypass")
    c.act("gather","stone")
    check(not c.act("place","support",false) and c.inventory.stone == 1,"invalid placement preserves material")
    c.act("cancel")
    check(c.inventory.stone == 1,"cancel preserves material")
    check(c.act("place","support"),"retry at actual support")
    check(not c.act("gather","stone"),"finite supply exhausted")
    for item in ["board","seal"]: c.act("gather",item)
    check(not c.act("place","seal"),"seal requires channel")
    c.act("place","channel")
    c.act("place","seal")
    c.act("inlet")
    for n in range(10): c.tick(10)
    check(c.flow.cell_state(1).water > .1 and c.flow.cell_state(3).water == 0 and c.flow.cell_state(3).soil == 0,"high actual outlet sill ponds; no row flow")
    c.act("grade")
    for n in range(20): c.tick(10)
    check(c.flow.cell_state(3).soil > .015,"lower actual sill delivers row water")
    check(c.earned,"row plus catchment observed")
    check(absf(c.flow.balance_error_m3()) < .000001,"conservation diagnostic")
    var other = preload("res://scripts/irrigation_construction.gd").new()
    check(other.restore(c.snapshot()),"snapshot replay valid")
    check(absf(other.flow.stored_m3()-c.flow.stored_m3()) < .000001,"reload preserves water and soil")
    check(other.inventory == c.inventory and other.installed == c.installed,"reload preserves finite construction")
    check(not other.restore({"version":1,"history":[{"seconds":-2}]}),"invalid replay rejected atomically")
    check(c.act("outlet") and c.act("inlet") and c.act("outlet") and c.act("inlet"),"free gate order")
    print("CONSTRUCTION_FAILURES=",failures)
    quit(failures)
