extends SceneTree
const Flow = preload("res://scripts/irrigation_flow.gd")
var checks := 0
var failures := 0

func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok:
		failures += 1
		printerr("FAIL: ", message)

func balanced(f) -> void:
	check(absf(f.balance_error_m3()) < 1e-9, "mass conservation")
	for i in range(f._cells.size()):
		var c: Dictionary = f.cell_state(i)
		check(c.water >= -1e-14 and c.water <= c.capacity + 1e-12 and c.soil >= 0.0 and c.soil <= c.soil_capacity, "bounded storage")

func pair(water: float = 1.0):
	var f = Flow.new()
	f.add_cell(0, 1, 1, 2, water)
	f.add_cell(0, 1, 1, 2)
	f.add_link(0, 1, 0, 0.1)
	return f

func _initialize() -> void:
	var f = pair(0)
	check(f.step(10), "dry step accepted")
	check(f.stored_m3() == 0, "dry network cannot create water")
	balanced(f)
	f = pair()
	f.step(100)
	check(absf(f.cell_state(0).head_m - f.cell_state(1).head_m) < 1e-7, "level equilibration")
	balanced(f)
	# Reverse head is allowed: this is not an ordered directed-switch puzzle.
	f = pair(0)
	f.set_boundary(1, 0.1)
	f.step(5)
	check(f.cell_state(0).water > 0, "backwater reverse flow")
	balanced(f)
	f = Flow.new()
	f.add_cell(0, 1, 1, 2, 0.4)
	f.add_cell(0.5, 1, 1, 1)
	f.add_link(0, 1, 0, 0.2)
	f.step(2)
	check(f.cell_state(1).water == 0, "uphill bed blocks insufficient head")
	f.set_boundary(0, 0.2)
	f.step(5)
	check(f.cell_state(1).water > 0, "higher bed can receive when source head exceeds sill")
	balanced(f)
	f = pair()
	f.set_opening(0, 0)
	f.step(2)
	check(f.cell_state(1).water == 0, "closed gate")
	f.set_opening(0, 1)
	f.set_broken(0, true)
	f.step(2)
	check(f.cell_state(1).water == 0, "broken connection cannot teleport water")
	f.set_broken(0, false)
	f.step(2)
	check(f.cell_state(1).water > 0, "rebuilt connection conducts")
	balanced(f)
	# Leak is a separate physical opening into a low catchment, seal closes it.
	f = Flow.new()
	f.add_cell(1, 1, 1, 1, 0.5)
	f.add_cell(0, 1, 1, 0.8)
	var leak: int = f.add_link(0, 1, 1, 0.1, 1, true)
	f.step(2)
	check(f.cell_state(1).water > 0, "leak reaches catchment")
	f.set_opening(leak, 0)
	var before: float = f.cell_state(0).water
	f.step(2)
	check(f.cell_state(0).water == before, "seal repair stops leak")
	balanced(f)
	f = Flow.new()
	f.add_cell(0.1, 1, 1, 1, 0.8)
	f.add_cell(0, 2, 0.2, 1, 0, 0.2, 0.001)
	f.add_cell(0, 2, 0.2, 1, 0, 0.2, 0.001)
	f.add_link(0, 1, 0.1, 0.05)
	f.add_link(0, 2, 0.1, 0.05)
	f.step(10)
	check(f.cell_state(1).soil > 0 and f.cell_state(2).soil > 0, "both branched furrows infiltrate")
	check(absf(f.cell_state(1).water - f.cell_state(2).water) < 1e-12, "symmetric branch fairness")
	balanced(f)
	f = Flow.new()
	f.add_cell(1, 1, 1, 0.1)
	f.add_cell(0, 1, 1, 0.2)
	check(f.set_overflow(0, 1), "designated lower overflow pond")
	check(not f.set_overflow(1, 0), "reject uphill spill or cycle")
	f.set_boundary(0, 0.1)
	f.step(2)
	check(f.cell_state(1).water > 0, "overflow captured before drain")
	f.step(3)
	check(f.overflow_out_m3 > 0, "finite pond also spills with mass ledger")
	f.set_boundary(0, 0)
	f.set_boundary(1, 0, 0.05)
	var pond_before: float = f.cell_state(1).water
	f.step(2)
	check(f.cell_state(1).water < pond_before and f.sink_m3 > 0, "pond drains to external river")
	balanced(f)
	var coarse = pair()
	var fine = pair()
	coarse.step(10)
	for i in range(1000):
		fine.step(0.01)
	check(absf(coarse.cell_state(0).water - fine.cell_state(0).water) < 0.001, "timestep refinement within 0.001 m3")
	print("Timestep difference m3: ", absf(coarse.cell_state(0).water - fine.cell_state(0).water))
	balanced(coarse)
	balanced(fine)
	f = pair()
	for bad in [-1.0, NAN, INF]:
		var state: float = f.stored_m3()
		check(not f.step(bad), "reject invalid time")
		check(not f.set_boundary(0, bad), "reject invalid source")
		check(not f.set_opening(0, bad), "reject invalid gate")
		check(f.add_cell(0, bad, 1, 1) == -1, "reject invalid geometry")
		check(f.add_link(0, 1, 0, bad) == -1, "reject invalid conductance")
		check(f.stored_m3() == state, "invalid operation is atomic")
	check(not f.step(1000000), "bounded computational work")
	check(f.add_cell(NAN, 1, 1, 1) == -1, "reject nonfinite bed")
	check(f.add_cell(0, 1, 1, 1, -0.1) == -1, "reject negative initial water")
	check(f.add_cell(0, 1, 1, 1, 0, -0.1) == -1, "reject negative soil capacity")
	check(f.add_cell(0, 1, 1, 1, 0, 0, INF) == -1, "reject infinite infiltration")
	balanced(f)
	# Saturation retains soil mass and leaves later supply on the surface.
	f = Flow.new()
	f.add_cell(0, 1, 1, 1, 0.5, 0.1, 1.0)
	f.step(1)
	check(absf(f.cell_state(0).soil - 0.1) < 1e-12, "soil saturation")
	check(absf(f.cell_state(0).water - 0.4) < 1e-12, "saturated soil leaves surface water")
	balanced(f)
	# Many transfers, repeated boundaries and tiny volumes stay nonnegative.
	f = Flow.new()
	f.add_cell(0, 1, 1, 1, 0.001)
	for i in range(12):
		f.add_cell(0, 0.1, 0.1, 1, 0, 0.001, 0.01)
		f.add_link(0, i + 1, 0, 0.2)
	f.set_boundary(0, 0.002)
	for i in range(30):
		check(f.step(0.1), "stiff branched network advances")
		for j in range(13):
			check(f.cell_state(j).water >= 0.0, "strict nonnegative water")
	balanced(f)
	print("IRRIGATION_FLOW: ", checks, " checks, ", failures, " failures")
	quit(0 if failures == 0 else 1)
