import objects from './object-edits.json'

export interface Difference { id: number; nameEn: string; nameRu: string; polygon: number[][]; hitMask: string; anchor: number[] }
export const SCENES = [
  { id: 'water-to-wine', titleEn: 'Water into Wine', titleRu: 'Вода в вино',
    storyEn: 'At a wedding in Cana, Jesus told the servants to fill six stone jars with water. He turned the water into wine. His disciples saw His glory and believed in Him.',
    storyRu: 'На свадьбе в Кане Иисус велел слугам наполнить шесть каменных сосудов водой. Он превратил воду в вино. Ученики увидели Его славу и поверили в Него.',
    verseEn: 'This, the first of his signs, Jesus did at Cana in Galilee, and manifested his glory. And his disciples believed in him.',
    verseRu: 'Так положил Иисус начало чудесам в Кане Галилейской и явил славу Свою; и уверовали в Него ученики Его.',
    refEn: 'John 2:11', refRu: 'Иоанна 2:11', source: 'JHN.2.11' },
  { id: 'feeding-5000', titleEn: 'Jesus Feeds the Crowd', titleRu: 'Иисус кормит людей',
    storyEn: 'A boy had five loaves and two fish. Jesus gave thanks and fed the hungry crowd. The disciples gathered twelve baskets of leftovers.',
    storyRu: 'У мальчика было пять хлебов и две рыбы. Иисус поблагодарил Бога и накормил голодных людей. Ученики собрали двенадцать корзин оставшихся кусков.',
    verseEn: 'And they all ate and were satisfied. And they took up twelve baskets full of the broken pieces left over.',
    verseRu: 'И ели все и насытились; и набрали оставшихся кусков двенадцать коробов полных',
    refEn: 'Matthew 14:20', refRu: 'Матфея 14:20', source: 'MAT.14.20' },
  { id: 'calm-storm', titleEn: 'Jesus Calms the Storm', titleRu: 'Иисус усмиряет бурю',
    storyEn: 'A storm frightened the disciples as they crossed the lake. Jesus commanded the wind and sea to be still. They obeyed Him! The disciples wondered at His power.',
    storyRu: 'На озере началась буря. Ученики испугались. Иисус повелел ветру и морю утихнуть — и они послушались! Ученики удивились Его силе.',
    verseEn: 'Who then is this, that even the wind and the sea obey him?',
    verseRu: 'кто же Сей, что и ветер и море повинуются Ему?',
    refEn: 'Mark 4:41', refRu: 'Марка 4:41', source: 'MRK.4.41' },
  { id: 'zacchaeus', titleEn: 'Zacchaeus in the Tree', titleRu: 'Закхей на дереве',
    storyEn: 'Zacchaeus climbed a tree to see Jesus. Jesus called him down and came to his home. Zacchaeus promised to give to the poor and repay anyone he had cheated.',
    storyRu: 'Закхей залез на дерево, чтобы увидеть Иисуса. Иисус позвал его и пришёл к нему домой. Закхей обещал помочь бедным и возместить ущерб тем, кого обманул.',
    verseEn: 'For the Son of Man came to seek and to save the lost.',
    verseRu: 'ибо Сын Человеческий пришел взыскать и спасти погибшее.',
    refEn: 'Luke 19:10', refRu: 'Луки 19:10', source: 'LUK.19.10' },
  { id: 'good-samaritan', titleEn: 'The Good Samaritan', titleRu: 'Добрый самарянин',
    storyEn: 'In the story Jesus told, a hurt man needed help. A Samaritan stopped, cared for him, and paid for a place to rest. Jesus teaches us to show mercy to our neighbor.',
    storyRu: 'В притче Иисуса раненому человеку нужна была помощь. Самарянин остановился, позаботился о нём и оплатил ночлег. Иисус учит нас проявлять милость к ближнему.',
    verseEn: 'You go, and do likewise.', verseRu: 'иди, и ты поступай так же.',
    refEn: 'Luke 10:37', refRu: 'Луки 10:37', source: 'LUK.10.37' },
  { id: 'lost-sheep', titleEn: 'The Lost Sheep', titleRu: 'Потерянная овца',
    storyEn: 'Jesus told of a shepherd who searched for one lost sheep. When he found it, he carried it home with joy. Jesus seeks and saves the lost.',
    storyRu: 'Иисус рассказал о пастухе, который искал потерянную овцу. Найдя её, он с радостью понёс её домой. Иисус ищет и спасает потерянных.',
    verseEn: 'Rejoice with me, for I have found my sheep that was lost.',
    verseRu: 'порадуйтесь со мною: я нашел мою пропавшую овцу.',
    refEn: 'Luke 15:6', refRu: 'Луки 15:6', source: 'LUK.15.6' },
  { id: 'daniel-lions', titleEn: 'Daniel and the Lions', titleRu: 'Даниил и львы',
    storyEn: 'Daniel kept praying to God. He was thrown into a den of lions, but God sent His angel and protected him. Daniel trusted God.',
    storyRu: 'Даниил продолжал молиться Богу. Его бросили в ров со львами, но Бог послал Своего ангела и защитил его. Даниил доверял Богу.',
    verseEn: 'My God sent his angel and shut the lions’ mouths',
    verseRu: 'Бог мой послал Ангела Своего и заградил пасть львам',
    refEn: 'Daniel 6:22', refRu: 'Даниила 6:22', source: 'DAN.6.22' },
  { id: 'empty-tomb', titleEn: 'The Empty Tomb', titleRu: 'Пустая гробница',
    storyEn: 'Women came to the tomb and found the stone rolled away. An angel told them that Jesus had risen, just as He said. Jesus is alive!',
    storyRu: 'Женщины пришли ко гробу и увидели, что камень отвален. Ангел сказал им: Иисус воскрес, как и обещал. Иисус жив!',
    verseEn: 'He is not here, for he has risen, as he said.',
    verseRu: 'Его нет здесь — Он воскрес, как сказал.',
    refEn: 'Matthew 28:6', refRu: 'Матфея 28:6', source: 'MAT.28.6' },
].map(scene => ({ ...scene, differences: objects.find(item => item.id === scene.id)!.differences as Difference[] }))

// Quotes/excerpts checked against Bible.com ESV (59) and Synodal (400).
export const scriptureSource = (source: string, ru: boolean) => `https://www.bible.com/bible/${ru ? '400' : '59'}/${source}.${ru ? 'SYNO' : 'ESV'}`
