// Reused Junior Disciples artwork, not newly commissioned lesson illustrations.
export const images = [
  '/images/jr/topic-case-for-christ-bible.png',
  '/images/jr/who-is-jesus-resurrection.png',
  '/images/jr/topic-case-for-christ-bible.png',
  '/images/jr/quests/fruit-of-spirit/03-scene-kindness-orchard.png',
  '/images/jr/topic-case-for-christ-bible.png',
  '/images/jr/quests/fruit-of-spirit/03-scene-kindness-orchard.png',
]
export const copy = {
  en: {
    title: "Know God's Word. Let It Change Your Life.",
    intro: "Jesus is alive! His Word helps us know Him, rethink our ideas, and grow in love. Explore four connected truths—then choose one small step for today.",
    all:'All lessons', progress:'Truths explored', start:'Begin the discovery', play:'Try the activity', next:'Next truth', learn:'Discover why', finish:'Choose my next step', check:'Check my order', undo:'Undo', clear:'Start the order again', hint:'Need a clue?', retry:'Not quite. Try again.', success:'You found it!',
    phases:['See','Do','Feedback','Learn'], saved:'Your place saves on this device when storage is available.', sessionOnly:'Saving is unavailable. You can keep learning here; reloading may lose your place.',
    titles:['1. God is living—and gives life','2. Let Scripture correct your ideas','3. Live what you learn','4. Check exciting claims with Scripture'],
    teaching:[
      'Some people told Jesus that the dead would not rise. Jesus showed them that they did not know the Scriptures or God’s power. God can raise the dead. Jesus rose bodily from death; those who belong to Him have hope of resurrection and life with Him.',
      'That same Word can correct us. Imagine thinking, “If I know a Bible answer, I do not need to help anyone.” James says to do what the Word teaches, not only hear it. We change our idea—not God’s words.',
      'Now put that corrected idea into practice! Knowing the word “kindness” is not the same as helping. God saves us by grace—His gift, not something we earn. His Spirit helps us grow in patience, kindness, and self-control.',
      'Love for God can bring joy! But an exciting feeling or a confident speaker does not prove that a claim is true. The Bereans listened eagerly and checked the Scriptures. We can do both too.',
    ],
    tasks:[
      'What did Jesus mean? Choose the answer that fits the whole Bible scene.',
      'Build a wise response. Tap the three steps in order, then check.',
      'Match each moment to a loving response. First tap a moment; then tap an action.',
      'Read each claim. Does it fit the Bible teaching you just explored?',
    ],
    choices:[
      'God’s power means I will never feel sad or get hurt.',
      'God can raise the dead. Jesus gives His people hope of life with Him.',
      'God’s power only means being cheerful and doing nice things.',
    ],
    choiceFeedback:[
      'Jesus promises resurrection and life with Him—not a life without sadness or pain now.',
      'Yes! This is real resurrection hope, not just a cheerful feeling.',
      'Kindness matters, but this passage is about God’s power to raise the dead. It is more than good behavior.',
    ],
    steps:['Read what the Bible says in its setting.','Let God’s Word correct my idea.','Ask God for help and act on His Word.'],
    moments:['Someone is taking a long turn.','A younger child drops a basket.','I want to shout when I lose.'],
    actions:['Pause, breathe, and speak gently.','Wait without grumbling.','Help pick things up.'],
    fruitFeedback:['Patience means waiting kindly, not pushing ahead. Which action shows that?','Kindness notices a need and helps. Which action helps with the basket?','Self-control means not letting anger choose our words. Which action slows an angry response?'],
    claims:['“I feel excited, so everything this video says about God must be true.”','“Even a confident speaker’s message should be checked with Scripture.”','“I know lots of Bible verses, so I can never make a mistake.”'],
    buckets:['Fits the teaching','Needs correction'],
    claimFeedback:['Excitement is a feeling, not proof. Compare the message with Scripture.','Checking Scripture is wise even when someone sounds certain. We can ask a trusted adult to read with us.','We can still make mistakes. Scripture helps us stay humble, learn, and accept correction.'],
    hints:[
      'Jesus was answering people who denied resurrection. Think about God’s power to give life, not a promise of easy days.',
      'First listen to what Scripture says. Next change your idea. Then put what you learned into practice.',
      'Waiting shows patience. Helping shows kindness. Pausing before angry words shows self-control.',
      'A message needs to agree with Scripture. Strong feelings, confidence, or knowing many verses do not make anyone unable to be wrong.',
    ],
    learns:[
      'Our hope begins with the living Jesus, not with our own strength. Because He lives, His people will live with Him. We can grieve and still have hope.',
      'We do not bend Scripture to fit what we want. We read in context, ask for help, and let God correct us. Jesus Christ is the foundation of His Church; Scripture teaches us His truth.',
      'Good actions do not buy God’s love or salvation. Jesus saves by grace. Patience and kindness grow as His Spirit helps us obey. When we fail, we can ask forgiveness and try again with His help.',
      'Keep the four truths together: trust the living Jesus, let His Word correct you, live it with His help, and check what you hear. We keep learning humbly—not claiming we can never be wrong.',
    ],
    done:'Four truths. One step today.', doneText:'This is practice, not a test of whether God loves you. Choose one response to His grace. You can ask a grown-up to help.',
    planTitle:'Today, with God’s help, I will…', plans:['Read John 14:19 with a grown-up and talk about Jesus’ promise.','Practice patience or kindness, then tell someone how it went.','Read a Bible passage with a trusted adult before believing a claim.'],
    commit:'Save my next step', completed:'Lesson complete—now take your step!', planSaved:'My next step:', prayer:'Jesus, thank You for giving life and loving us first. Help me listen to Your Word and live it with Your help. Amen.',
    again:'Explore again', nextLesson:'Explore grace next', parent:'For grown-ups: sources and teaching notes',
    note:'Adapted from the FSBC Charlotte morning sermon, September 27, 2026, BoxCast 01:01:31–01:32:08. This child adaptation keeps four connected teachings, not the adult illustrations. Matthew 22:23–33 concerns resurrection; practical growth is an application, not a replacement for that meaning. Christ is the foundation (1 Corinthians 3:11); grace comes before our works (Ephesians 2:8–10). In 1 Thessalonians 5:19–22, Paul also warns against rejecting the Spirit’s work or despising prophecy: testing means listening carefully and keeping what is good, not dismissing every spiritual experience. Bible learning does not make us immune to mistakes. Progress measures activities, never salvation or God’s love. Read together and invite questions.',
    source:'Original service (adult source)', art:'Artwork reused from existing Junior Disciples Bible, resurrection, and Fruit of the Spirit lessons/quest. These are illustrations, not historical photographs or newly generated art.',
    alts:['An illustrated Bible, cross, and magnifying glass invite careful reading.','An illustration of an empty tomb at sunrise points to resurrection hope.','An open Bible and magnifying glass picture looking closely at Scripture.','Children help a younger child gather spilled fruit in an orchard.','A magnifying glass beside a Bible pictures checking what we hear.','Children show kindness by helping gather spilled fruit.'],
  },
  ru: {
    title:'Узнавай Божье Слово. Пусть оно меняет твою жизнь.',
    intro:'Иисус жив! Его Слово помогает нам узнать Его, исправлять свои мысли и расти в любви. Открой четыре важные истины, а потом выбери один шаг на сегодня.',
    all:'Все уроки', progress:'Истины изучены', start:'Начать открытие', play:'Попробовать задание', next:'Следующая истина', learn:'Узнать почему', finish:'Выбрать свой шаг', check:'Проверить порядок', undo:'Отменить шаг', clear:'Собрать заново', hint:'Нужна подсказка?', retry:'Пока не совсем так. Попробуй ещё.', success:'Верно!',
    phases:['Смотри','Действуй','Проверь','Узнай'], saved:'Если устройство разрешает, твой прогресс сохранится.', sessionOnly:'Не удаётся сохранить. Ты можешь продолжать, но после перезагрузки прогресс может пропасть.',
    titles:['1. Бог живой — и Он даёт жизнь','2. Пусть Писание исправляет твои мысли','3. Живи по тому, что узнаёшь','4. Проверяй услышанное по Писанию'],
    teaching:[
      'Некоторые люди говорили Иисусу, что мёртвые не воскреснут. Иисус показал: они не знают Писания и Божьей силы. Бог может воскресить мёртвых. Иисус воскрес по-настоящему, в теле. У тех, кто принадлежит Ему, есть надежда на воскресение и жизнь с Ним.',
      'Божье Слово исправляет и нас. Представь такую мысль: «Я знаю ответ из Библии, значит, помогать никому не нужно». Иаков учит не только слушать Слово, но и исполнять его. Менять нужно нашу мысль, а не Божьи слова.',
      'Теперь пора поступить по тому, что ты узнал! Знать слово «доброта» — не то же самое, что помочь. Бог спасает нас по благодати — это Его дар, который нельзя заслужить. Его Дух помогает нам расти в терпении, доброте и умении владеть собой.',
      'Любовь к Богу приносит радость! Но яркое чувство или уверенный голос ещё не доказывают, что слова верны. Жители Верии охотно слушали проповедь и проверяли её по Писанию. Мы тоже можем так делать.',
    ],
    tasks:[
      'Что имел в виду Иисус? Выбери ответ, который подходит к этой библейской истории.',
      'Собери мудрый ответ. Нажми на три шага по порядку, а потом проверь.',
      'Подбери добрый поступок к каждой ситуации. Сначала нажми на ситуацию, потом — на поступок.',
      'Прочитай каждую мысль. Совпадает ли эта мысль с тем, чему учит Библия?',
    ],
    choices:[
      'Божья сила означает, что мне никогда не будет грустно или больно.',
      'Бог может воскресить мёртвых. Иисус даёт Своим людям надежду на жизнь с Ним.',
      'Божья сила — это только хорошее настроение и добрые дела.',
    ],
    choiceFeedback:[
      'Иисус обещает воскресение и жизнь с Ним, а не жизнь без грусти и боли сейчас.',
      'Да! Это настоящая надежда на воскресение, а не просто радостное чувство.',
      'Доброта важна, но здесь говорится о Божьей силе воскресить мёртвых. Это больше, чем хорошее поведение.',
    ],
    steps:['Прочитать, что говорит Библия, и понять смысл отрывка.','Позволить Божьему Слову исправить мою мысль.','Попросить Бога помочь и поступить по Его Слову.'],
    moments:['Кто-то долго играет, а я жду своей очереди.','Малыш уронил корзинку.','Мне хочется кричать, когда я проигрываю.'],
    actions:['Остановиться, вздохнуть и ответить спокойно.','Подождать без ворчания.','Помочь всё собрать.'],
    fruitFeedback:['Терпение — это ждать по-доброму, а не лезть вперёд. Какой поступок подходит?','Доброта замечает нужду и помогает. Как помочь малышу с корзинкой?','Владеть собой — значит не давать злости выбирать наши слова. Что поможет ответить спокойно?'],
    claims:['«Мне так нравится это видео! Значит, всё, что в нём говорят о Боге, — правда».','«Даже слова уверенного человека нужно проверять по Писанию».','«Я знаю много стихов из Библии, поэтому никогда не ошибаюсь».'],
    buckets:['Согласуется с Библией','Нужно исправить'],
    claimFeedback:['Восторг — это чувство, а не доказательство. Сравни слова с Писанием.','Проверять по Писанию мудро, даже если человек говорит уверенно. Можно попросить взрослого прочитать вместе.','Мы всё ещё можем ошибаться. Писание помогает нам учиться, быть скромнее и принимать исправление.'],
    hints:[
      'Иисус отвечал людям, которые не верили в воскресение. Подумай о Божьей силе дать жизнь, а не о жизни без трудностей.',
      'Сначала узнай, что говорит Писание. Затем исправь свою мысль. Потом поступи по тому, что узнал.',
      'Ждать — это терпение. Помогать — это доброта. Остановиться перед сердитым ответом — это умение владеть собой.',
      'Слова должны быть согласны с Писанием. Яркие чувства, уверенность или знание многих стихов не защищают от всех ошибок.',
    ],
    learns:[
      'Наша надежда — в живом Иисусе, а не в наших силах. Он жив, и Его люди будут жить с Ним. Даже когда нам грустно, у нас есть надежда.',
      'Мы не подгоняем Писание под свои желания. Мы читаем внимательно, просим помощи и принимаем Божье исправление. Иисус Христос — основание Его Церкви. Писание учит нас Его истине.',
      'Добрыми делами нельзя купить Божью любовь или спасение. Иисус спасает по благодати. Его Дух помогает нам быть терпеливыми и добрыми. Если мы ошиблись, можно попросить прощения и снова попробовать с Его помощью.',
      'Помни все четыре истины: доверяй живому Иисусу, принимай исправление из Его Слова, живи по нему с Его помощью и проверяй услышанное. Мы продолжаем учиться, а не говорим: «Я никогда не ошибаюсь».',
    ],
    done:'Четыре истины. Один шаг сегодня.', doneText:'Это тренировка, а не проверка того, любит ли тебя Бог. Выбери один ответ на Его благодать. Можно попросить взрослого помочь.',
    planTitle:'Сегодня с Божьей помощью я…', plans:['Прочитаю Иоанна 14:19 со взрослым и поговорю об обещании Иисуса.','Проявлю терпение или доброту, а потом расскажу, как получилось.','Прочитаю отрывок из Библии со взрослым, которому доверяю, прежде чем поверить чьим-то словам.'],
    commit:'Сохранить мой шаг', completed:'Урок пройден — теперь сделай свой шаг!', planSaved:'Мой шаг:', prayer:'Иисус, спасибо, что Ты даёшь жизнь и первым возлюбил нас. Помоги мне слушать Твоё Слово и жить по нему с Твоей помощью. Аминь.',
    again:'Пройти ещё раз', nextLesson:'Дальше — о благодати', parent:'Для взрослых: источники и пояснения',
    note:'Детский урок по утренней проповеди FSBC Charlotte от 27 сентября 2026 года, BoxCast 01:01:31–01:32:08. Сохранены четыре связанные мысли, без взрослых примеров. Матфея 22:23–33 говорит о воскресении. Духовный рост — применение текста, а не замена его смысла. Основание Церкви — Христос (1 Коринфянам 3:11); благодать предшествует делам (Ефесянам 2:8–10). В 1 Фессалоникийцам 5:19–22 Павел также предупреждает: не угашать Духа и не презирать пророчества. Проверять — значит внимательно слушать и держаться доброго, а не отвергать всякий духовный опыт. Знание Библии не делает нас безошибочными. Прогресс отмечает задания, а не спасение или Божью любовь. Читайте вместе и обсуждайте вопросы ребёнка.',
    source:'Запись богослужения (источник для взрослых)', art:'Повторно использованы иллюстрации Junior Disciples о Библии, воскресении и плоде Духа. Это рисунки, а не исторические фотографии или новая графика для этого урока.',
    alts:['Библия, крест и лупа приглашают к внимательному чтению.','Иллюстрация пустой гробницы на рассвете напоминает о воскресении.','Открытая Библия и лупа напоминают о внимательном чтении Писания.','Дети помогают малышу собрать рассыпанные фрукты в саду.','Лупа рядом с Библией напоминает: услышанное нужно проверять.','Дети проявляют доброту и помогают собрать фрукты.'],
  },
}
